# Generated by Django 3.2.5 on 2022-04-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='icylUser',
        ),
    ]
