# Generated by Django 3.2.5 on 2022-04-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1_name', models.CharField(blank=True, max_length=500, null=True)),
                ('field1', models.TextField(blank=True, null=True)),
                ('field2_name', models.CharField(blank=True, max_length=500, null=True)),
                ('field2', models.TextField(blank=True, null=True)),
                ('field3_name', models.CharField(blank=True, max_length=500, null=True)),
                ('field3', models.TextField(blank=True, null=True)),
                ('field4_name', models.CharField(blank=True, max_length=500, null=True)),
                ('field4', models.TextField(blank=True, null=True)),
                ('num1_name', models.CharField(blank=True, max_length=500, null=True)),
                ('num1', models.CharField(blank=True, max_length=500, null=True)),
                ('num2_name', models.CharField(blank=True, max_length=500, null=True)),
                ('num2', models.CharField(blank=True, max_length=500, null=True)),
                ('num3_name', models.CharField(blank=True, max_length=500, null=True)),
                ('num3', models.CharField(blank=True, max_length=500, null=True)),
                ('num4_name', models.CharField(blank=True, max_length=500, null=True)),
                ('num4', models.CharField(blank=True, max_length=500, null=True)),
                ('date1_name', models.DateField(blank=True, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2_name', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3_name', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('date4_name', models.DateField(blank=True, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_category', models.CharField(blank=True, max_length=500, null=True)),
                ('discount_percent', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Primmary_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.CharField(blank=True, max_length=500, null=True)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.event_information')),
            ],
        ),
        migrations.CreateModel(
            name='event_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.category')),
                ('contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.primmary_contact')),
                ('custom_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.custom_information')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.discount')),
                ('fees_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.fees')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='fees_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icyl_app.fees'),
        ),
    ]
