# Generated by Django 3.2.5 on 2022-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0002_rename_user_icyluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
            ],
        ),
    ]
