# Generated by Django 3.2.5 on 2022-03-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0003_alter_committee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='iqamat_time',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='namas_time',
        ),
    ]
