# Generated by Django 3.2.5 on 2022-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0003_excelfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurancompetetion',
            name='order_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qurancompetetion',
            name='time_slot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
