# Generated by Django 3.2.5 on 2022-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0004_auto_20220310_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='iqamat_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='namas_time',
            field=models.TimeField(null=True),
        ),
    ]
