# Generated by Django 3.2.5 on 2022-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0009_prayer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_banner', models.FileField(upload_to='images/')),
                ('footer', models.FileField(upload_to='images/')),
                ('logo', models.CharField(max_length=200)),
                ('main_menu', models.CharField(max_length=500)),
                ('post1', models.CharField(max_length=500)),
            ],
        ),
    ]
