# Generated by Django 3.2.5 on 2022-03-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0010_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='logo',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='main_menu',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='post1',
            field=models.FileField(upload_to='images/'),
        ),
    ]
