# Generated by Django 3.2.5 on 2022-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0012_cardbanner1_cardbanner2_cardbanner3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='iqamat_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='namas_time',
            field=models.DateTimeField(null=True),
        ),
    ]
