# Generated by Django 3.2.5 on 2022-03-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0013_auto_20220317_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='banner_image2',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='banner_image3',
        ),
    ]
