# Generated by Django 3.2.5 on 2022-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0014_auto_20220318_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='donations',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
