# Generated by Django 3.2.5 on 2022-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icyl_app', '0015_index_donations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
